version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ZeroRedact.DemoSite"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    target-branch: "main"
    allow:
      - dependency-name: "Nikouu.ZeroRedact"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]
    automerge: true
    automerge-type: "pr"
    labels:
      - "dependencies"
      - "automerge"