// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "Makes it easier for the user.", Scope = "namespace", Target = "~N:ZeroRedact")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "New redactor instance for DI.", Scope = "member", Target = "~M:ZeroRedact.ZeroRedactExtensions.AddZeroRedact(Microsoft.Extensions.DependencyInjection.IServiceCollection,ZeroRedact.RedactorOptions)~Microsoft.Extensions.DependencyInjection.IServiceCollection")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactStringInternal(System.ReadOnlySpan{System.Char},ZeroRedact.Options.Internal.InternalStringRedactorOptions)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactPhoneNumberInternal(System.ReadOnlySpan{System.Char},ZeroRedact.Options.Internal.InternalPhoneNumberRedactorOptions)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactMACAddressInternal(System.ReadOnlySpan{System.Char},ZeroRedact.Options.Internal.InternalMACAddressRedactorOptions)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactIPv4Internal(System.ReadOnlySpan{System.Char},ZeroRedact.Options.Internal.InternalIPv4AddressRedactorOptions)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactEmailInternal(System.ReadOnlySpan{System.Char},ZeroRedact.Options.Internal.InternalEmailAddressRedactorOptions,System.Boolean)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactDateInternal(System.DateOnly,ZeroRedact.Options.Internal.InternalDateRedactorOptions)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Creating a new exception.", Scope = "member", Target = "~M:ZeroRedact.Redactor.RedactCreditCardInternal(System.ReadOnlySpan{System.Char},ZeroRedact.Options.Internal.InternalCreditCardRedactorOptions)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Have to make the final string to return.", Scope = "member", Target = "~M:ZeroRedact.Redactor.CreateAllDateRedaction(System.DateOnly,System.Char)~System.String")]
[assembly: SuppressMessage("Performance", "HAA0502:Explicit new reference type allocation", Justification = "Have to make the final string to return.", Scope = "member", Target = "~M:ZeroRedact.Redactor.CreateAllRedaction(System.Char,System.Int32)~System.String")]
